### ISSUE TITLE
Should we allow single-line if statements?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#11]
Should the following be allowed,

    if a then 1 else 2

or should we always convert it to the multiline version?

    if a then
        1
    else
        2

**Comment by Apanatshka** [comment]
For now I would always convert to multiline, because it's simple and foolproof. If later we find out that it's too annoying in some places with small if statements, we can always reconsider. At that point we'll probably have to consider more complicated rules for nice formatting of expressions anyway, which will be a hard problem if it's going to look anything like [dartfmt](http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/).

**Comment by rtfeldman** [comment]
I agree. +1 to what @Apanatshka said!

**Comment by avh4** [comment]
Okay, all if-statments will become multiline when formatted for now.  We can revisit this after seeing more real-world examples.
