### ISSUE TITLE
Should we automatically escape/unescape characters in strings?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#13]

**Comment by avh4** [comment]
See #5

**Comment by Apanatshka** [comment]
I'd preserve the escapes that were used in the original file. Seems like the simplest solution for now. 
Perhaps in a later version we can add an opinion in the formatter about escaping, but I suspect that it requires careful implementation because edge-cases can make the formatter output broken code.

**Comment by avh4** [comment]
For the implementation, it's easier to do this automatically because the parser currently doesn't preserve the original escaping.  But I agree that the edge-cases are dangerous.

**Comment by rtfeldman** [comment]
I'd say leave it as-is for now, because this isn't something that should block an alpha release. Then I'd circle back to it once elm-format is at the point of "it's out in alpha or beta form, and people are trying it and giving feedback." We'll be checking our pull requests for surprises anyway. :smile:

**Comment by avh4** [comment]
I want to try doing this and see how it goes.  I think we should try to push for a normalized way to escape strings since it'll be harder to convince people later.

**Comment by avh4** [comment]
I implemented the following rules for now:

Should escape the following and remove escaping form everything else:
 - `\\`
 - `\n` except in `"""` strings
 - `\t`
 - `\"` in strings
 - `\'` in chars
 - any whitespace character except a normal space as `\xNN` or `\xNNNN`
 - any non-print character as `\xNN`, `\xNNNN`, or `\xNNNNN`

This will be good for the alpha release.  Open a new issue for further discussion about changing this.
