### ISSUE TITLE
Complex conditionals

### ISSUE THREAD

**Issue by chendrix** [avh4/elm-format#170]
Here's the various ways elm-format has formatted this, depending on whether I use infix operators, or parentheses, and where I've placed things before running it

``` elm
isLeapYear : Int -> Bool
isLeapYear n =
  (&&)
    (n `isDivisibleBy` 4)
    (not (n `isDivisibleBy` 100) || n `isDivisibleBy` 400)
```

``` elm
isLeapYear : Int -> Bool
isLeapYear n =
  (n `isDivisibleBy` 4)
    && (not (n `isDivisibleBy` 100) || n `isDivisibleBy` 400)
```

``` elm
isLeapYear : Int -> Bool
isLeapYear n =
  n
    `isDivisibleBy` 4
    && (not (n `isDivisibleBy` 100) || n `isDivisibleBy` 400)
```

``` elm
isLeapYear : Int -> Bool
isLeapYear n =
  (n
    `isDivisibleBy` 4
  )
    && ((not (n `isDivisibleBy` 100))
          || (n `isDivisibleBy` 400)
       )
```

I don't know which style I like the best, (maybe 1?), but it's certainly confusing that the tool settles on so many different kinds of formatting. Is it possible to make it smarter around this?

**Comment by Janiczek** [comment]
I think (1) would make sense if `(&&)` allowed for arbitrary number of arguments (think Clojure's `and`). That is to say, in Elm the most feasible way for this would be something like
```elm
all : List Bool -> Bool -- &&
any : List Bool -> Bool -- ||

isLeapYear n =
  all
    [ n `isDivisibleBy` 4
    , not (n `isDivisibleBy` 100) || n `isDivisibleBy` 400
    ]
```

But that's refactoring your code. Of all your examples (2) seems best to me (most idiomatic).

**Comment by mgold** [comment]
> allowed for arbitrary number of arguments
Without going into too much detail because it's off-topic, optional or arbitrary arguments can't be made to work with Elm's currying syntax. Also, `List.all` and `List.any` do exactly what you want, and I agree they are more idiomatic.

Here's another example of a complex conditional, horribly formatted. (Note that `A` is the only value constructor for `Animation` and holds a record.)

```elm
equals : Animation -> Animation -> Bool
equals (A a) (A b) =
  a.start
    + a.delay
    == b.start
    + b.delay
    && a.from
    == b.from
    && a.to
    == b.to
    && a.ramp
    == b.ramp
    && (a.dos == b.dos || 0.001 >= abs (dur a.dos a.from a.to - dur b.dos b.from b.to))
    && List.all (\t -> a.ease t == b.ease t) [ 0.1, 0.3, 0.7, 0.9 ]
```

This is so bad that I'm not using elm-format for the project, and have [manually formatted the conditional](https://github.com/mgold/elm-animation/blob/9513a80ee3199c0b6867cef28ce19fb108895953/Animation.elm#L332-L339) as:

```elm
equals : Animation -> Animation -> Bool
equals (A a) (A b) =
  a.start + a.delay == b.start + b.delay &&
  a.from == b.from &&
  a.to == b.to &&
  a.ramp == b.ramp &&
  (a.dos == b.dos || 0.001 >= abs (dur a.dos a.from a.to - dur b.dos b.from b.to)) &&
  List.all (\t -> a.ease t == b.ease t) [0.1, 0.3, 0.7, 0.9]
```

**Comment by avh4** [comment]
Max's example can be formatted as

```elm
module Main exposing (..)


dosIsWithin range a b =
    if a.dos == b.dos then
        True
    else
        abs (dur a.dos a.from a.to - dur b.dos b.from b.to)
            <= range


equals : Animation -> Animation -> Bool
equals (A a) (A b) =
    (a.start + a.delay == b.start + b.delay)
        && (a.from == b.from)
        && (a.to == b.to)
        && (a.ramp == b.ramp)
        && (dosIsWithin 0.001 a b)
        && List.all (\t -> a.ease t == b.ease t) [ 0.1, 0.3, 0.7, 0.9 ]

-- or

equals : Animation -> Animation -> Bool
equals (A a) (A b) =
    List.all identity
        [ (a.start + a.delay == b.start + b.delay)
        , (a.from == b.from)
        , (a.to == b.to)
        , (a.ramp == b.ramp)
        , (dosIsWithin 0.001 a b)
        , List.all (\t -> a.ease t == b.ease t) [ 0.1, 0.3, 0.7, 0.9 ]
        ]
```

Unfortunately elm-format cannot use the associativity and precedence of infix operators to influence its indentation because this information is outside of the current file, and it is a constraint on elm-format that we want a given piece of elm code to have the same formatting independent of context, and also that we want to be able to format a file without having its entire project available.

**Comment by avh4** [comment]
For Chris' original example, I think I would use his (2), or

```elm
isLeapYear : Int -> Bool
isLeapYear n =
    (n `isDivisibleBy` 4)
        && ((not (n `isDivisibleBy` 100))
                || (n `isDivisibleBy` 400)
           )
```

**Comment by chendrix** [comment]
Yeah I like (2) as well

**Comment by avh4** [comment]
This appears to be resolved.

**Comment by mgold** [comment]
@avh4 The example I gave on May 10, 2016 is still formatted oddly by 0.6.1.
