### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by yurrriq** [avh4/elm-format#233]
In other ML family languages, I make habit of vertically aligning tokens like `:` and `=`. In my opinion, and I'm not alone (*citation needed*), this **greatly** enhances readability. It seems that elm-format disagrees with me.

<details>
<summary>For example, consider a record `Foo`.</summary>
```elm
type alias Foo =
    { bar   : String
    , baz   : String
    , other : List String
    }
```

If I run `elm-mode-format-buffer` in Emacs, I lose my vertical alignment.

```elm
type alias Foo =
    { bar : String
    , baz : String
    , other : List String
    }
```
</details>

<details>
<summary>Another contrived example.</summary>
```elm
setBarAndOther : String -> List String -> Foo -> Foo
setBarAndOther newBar newOther foo =
    { foo
        | bar   = newBar
        , other = newOther
    }
```

```elm
setBarAndOther : String -> List String -> Foo -> Foo
setBarAndOther newBar newOther foo =
    { foo
        | bar = newBar
        , other = newOther
    }
```
</details>

Perhaps this is a "feature not a bug" situation. If so, I'd like to learn the reasoning behind breaking vertical alignment. If not, please support vertical alignment.

Thanks!

**Comment by NobbZ** [comment]
Because aligning them is not allowed by the official elm-lang-styleguide.
You can find the example and the explanation in the types sections:
http://elm-lang.org/docs/style-guide#types

But you are right, there are some things I really don't like as well, since
I'm comming from haskell, and elm-format style is vertically bloated in my
opinion, so I just don't use elm-format, nor do I apply the styleguide in
any sense, also I do not publish any libraries.

Eric Bailey <notifications@github.com> schrieb am Fr., 9. Sep. 2016 um
22:55 Uhr:

**Comment by yurrriq** [comment]
Heh, fair enough. I guess my follow up question then is why doesn't the official style guide support/suggest vertical alignment?

**Comment by NobbZ** [comment]
Because it leads to bad diffs:

> If we ever add a new field to `Circle` that is longer than radius we have to change the indentation of all lines, leading to a bad diff. 

Its written in the guide.

**Comment by yurrriq** [comment]
I guess I don't agree and have no problem with using `-w` when diffing, but it's not my language.
