### ISSUE TITLE
Preserve indentation of comments labeling conditional branches

### ISSUE THREAD

**Issue by knuton** [avh4/elm-format#251]
When applying `elm-format` to an _if_ expression where the branches are labeled with comments, all comments but the first are indented one level too much:

```elm
module Main exposing (..)


x =
    -- This is the common case
    if 5 > 1 then
        "Everything is fine."
    -- Exceptional case
    else
        "Mayhem"
```

becomes 

```elm
module Main exposing (..)


x =
    -- This is the common case
    if 5 > 1 then
        "Everything is fine."
        -- Exceptional case
    else
        "Mayhem"
```

This works as I would expect on _case_ expressions.

**Comment by DavidHernandez** [comment]
I'm not sure if it will be related, but I'm experiencing a similar issue.

I have a complex record and I want to document it. This is how I expected it to look:
```
module Custom.Model exposing (..)

type alias CustomRecord =
     -- Comment
    { field : String
    , field2 : String
    -- Comment
    , field3 : String
    , field4 : String
  }
```
And this is how it looks:
```
module Custom.Model exposing (..)

type alias CustomRecord =
     -- Comment
    { field : String
    , field2 :
        String
        -- Comment
    , field3 : String
    , field4 : String
  }
```

**Comment by avh4** [comment]
elm-format currently takes the approach of attaching comments to the AST node that is being parsed when the elm-compiler parser consumes the adjacent whitespace.

In the case of
```elm
    if 5 > 1 then
        "Everything is fine."
    -- COMMENT
    else
        "Mayhem"
```
the comment is considered part of the body of the `if`, because the includes everything between `then` and `else`.  If might be reasonable to special-case the whitespace immediately before `else` keywords, but I would have some questions before doing that:
  - Do most/all developers expect a comment in that position to relate to the `else` clause rather than to the expression in the `if` body?
  - Are there any grey areas?  Clearly in this case, the comment belongs with the `if` body:

        if 5 > 1 then
            "Everything is fine." -- COMMENT
        else
            "Mayhem"

    Are there intermediate cases where it's not clear where the comment should attach to?  What if there are multiple comments before the else?

(Also, I think @DavidHernandez's example of records should be tracked in a separate issue.)

**Comment by knuton** [comment]
I started writing a response, but you know what: Maybe my desire to use this style is a relict from using imperative languages. In imperative languages, placing the comment in the first line of a block causes ambiguity: Does it relate to the whole branch or just its first statement?

In Elm, this doesn't seem to be a problem? I think it's fine to just write it as:

```elm
module Main exposing (..)


x =
    if 5 > 1 then
        -- This is the common case
        "Everything is fine."
    else
        -- Exceptional case
        "Mayhem"
```

@avh4 Thanks for the response! Closing this, but feel free to re-open if you disagree.

@DavidHernandez I think your issue is still legitimate, can you open a separate issue?
