### ISSUE TITLE
infixr inline comment

### ISSUE THREAD

**Issue by vshesh** [avh4/elm-format#345]
```elm
(::?) : Maybe a -> List a -> List a
(::?) elem list = ... 
infixr 5 ::? -- comment
```

comment gets attached to the next token, doesn't stay on the same line as the infix operator. Is this expected behavior?
If I put the comment above the infix token, it creates a 2 line gap before/after the comment, which also looks strange.

**Comment by avh4** [comment]
This is known current behavior, but is probably not ideal.  Not enough people have used custom infix operators to give good feedback on formatting for infixr/infixl.

Is it common to put `infixr` after the declaration/type annotation rather than before it?

And would this work for your case?  (Also not current elm-format behavior.)

```elm
{-| comment -}
infixr 5 ::?
(::?) : Maybe a -> List a -> List a
(::?) elem list = ... 
```

**Comment by avh4** [comment]
The recommended style is now:

```
{-| comment
-}
infixr 5 ::?
(::?) : Maybe a -> List a -> List a
(::?) elem list = ... 
```

00b86cf3...b4c90109

Please open a new issue if there's further discussion.
