### ISSUE TITLE
Add parentheses to import exposing clause if missing

### ISSUE THREAD

**Issue by andys8** [avh4/elm-format#510]
A common mistake I make quite often is forgetting parentheses for the types exposed when imorting data types. Here is an example:
```elm
-- Wrong
import Date exposing Date

-- Right
import Date exposing (Date)
```

The elm compiler will fail.
```shell
Failed to compile.

./src/Main.elm

-- SYNTAX PROBLEM ----------------------------------------------- ./src/Form.elm

I ran into something unexpected when parsing your code!

7| import Date exposing Date
                        ^
I am looking for one of the following things:

    a listing of values and types to expose, like (..)
    whitespace
```

How are the chances to having elm format fixing this automatically, which would awesome as hell? Can this be done in `elm-format` and would a pull request be merged?

**Comment by avh4** [comment]
I agree, this sounds like a good idea.

For adding lenient parser features, I want to make sure we think through any possible syntax ambiguities that we might introduce.  The only one I can think of at the moment is

```
import Date exposing as as D
```

(which is not legal Elm, since Elm requires the `as` clause come before the `exposing` clause, but possibly "exposing before as" might be something elm-format might want to allow and correct in the future)

In any case, I think a PR for this would be good.  I expect it would simply involve a change to the parser that parses import lines, and for this type of feature, should add a new test case in `tests/test-files/transform/`

**Comment by avh4** [comment]
I am tagging this for version 1.3.0, but if someone contributes a PR for this, I would be happy to include it in an earlier version.

**Comment by avh4** [comment]
This was implemented in https://github.com/avh4/elm-format/pull/513  Thanks!
