### ISSUE TITLE
plugin authors discussion w/rt 0.8.0 release

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#522]
From #519, @kachkaev says:

> Glad to see `0.8.0-rc3` @avh4! Given that [elm 0.19 has been just released](http://elm-lang.org/blog/small-assets-without-the-headache), I'm wondering how to proceed with upgrading [`prettier-plugin-elm`](https://github.com/gicentre/prettier-plugin-elm), which depends on elm-format.
> 
> How soon are you expecting `0.8.0` to go out? Shall I wait for this release or just bump `prettier-plugin-elm` with an RC?
> 
> Am I right in the assumption that `elm-format@0.8.0` still supports Elm `0.18`?

**Comment by avh4** [comment]
I'm planning to release 0.8.0 today.

The `npm install elm-format` will install the Elm 0.19 version.  There will be binaries to download for both the 0.19 and 0.18 version.  However, regardless of which binaries you use, all binaries support Elm 0.19, 0.18 and 0.17 if you use the `--elm-version=` flag.

Let me know if anything seems strange from the perspective of plugin authors.

**Comment by kachkaev** [comment]
In the case of `prettier-plugin-elm`, `elm-format` dependency is hard-link and its version is locked. This is intentional to simplify installation and to avoid compatibility issues.

Prettier plugins can be installed locally for a given project or globally using `npm install -g` / `yarn global add`, so there can be multiple sets of prettier plugins on a single machine. The same applies to elm binaries: there can be a local project-scoped elm and a global elm installed at the same time; their versions may differ.

Since you are mentioning `--elm-version=...` flag, it may be hypothetically possible for `prettier-plugin-elm`, to check the current version of elm and spoon-feed it to `elm-format`. But this makes things hard because `elm-format` can be given a wrong version of elm depending on the look of PATH (`./node_modules/.bin/prettier` and `yarn prettier` can give different results). Because of this intricate  relationship, I'm inclined not to use `--elm-version=...` flag at all and am wondering how likely `elm-format@0.8.0` will break elm files written for `elm@0.18`. Should I recommend users of `prettier-plugin-elm` to install a future version only if they have have switched to the new elm? In this case I guess I'll need to maintain two versions of the `prettier-plugin-elm` until elm 0.19 is used pretty much by everyone.

**Comment by avh4** [comment]
I think it's best to do the 0.8.0 release tonight, so I'm moving this discussion to the 0.8.1 milestone.

**Comment by avh4** [comment]
@kachkaev what did you end up recommending for prettier-plugin-elm users?  Do you know what the experience of your plugin users has been with Elm 0.19 so far?

**Comment by avh4** [comment]
One thing I've been considering is to say that plugins should prefer using `./node_modules/.bin/elm-format` if it exists in the current project, which would allow users to install the appropriate version locally with npm.  Would an option like that align with the philosophy of prettier?

**Comment by kachkaev** [comment]
Hi @avh4! I have not looked into upgrading to 0.8.0 so far due to lack of time, but I hope I'll do this in the next few weeks. Feel free to ping and poke me if I disappear again 😅 

In terms of using local `elm-format`: `prettier-plugin-elm` has got a hard dependency on `elm-format`, which gets automatically installed in the same place as the plugin. But this does not mean you cannot have multiple versions – there can be a project-specific prettier with a local prettier-plugin-elm version A and a global prettier with a global plugin version B, which depends on a different elm-format. I was thinking o loosing the dependency originally, but decided not to do so in the end. The reason is that we're [applying couple of formatting hacks](https://github.com/gicentre/prettier-plugin-elm#implementation-details) to support fragments, and these may break if the version of prettier-format is not predictable.

**Comment by kachkaev** [comment]
I upgraded `elm-format` in `prettier-plugin-elm` this weekend and released [a couple of RCs](https://github.com/gicentre/prettier-plugin-elm/releases). I'll go for supporting 0.19 only, because `elm.json` may not exist in the context of markdown code blocks. Once there is a decision on https://github.com/avh4/elm-format/issues/551, I guess I'll be able to make the new version stable.

**Comment by avh4** [comment]
Implemented in 0.8.1.  (plugins should pass `--elm-version=...`, or run elm-format from the directory containing elm.json/elm-package.json)

Also, created https://github.com/avh4/elm-format/issues/561 to slightly improve things more in 0.8.2.  (should allow any plugins that use `--yes` (and not `--stdin`) to not need to pass `--elm-version=...`)
