### ISSUE TITLE
Easier to package upstream

### ISSUE THREAD

**Issue by domenkozar** [avh4/elm-format#529]
Hi, as I'm packaging this for Nix, a few notes:

- sync up to latest LTS (remove indents-0.4.0.0 dependency)
- Setup.hs depends on git invocations, but we use tarball source that does not have `.git`

**Comment by avh4** [comment]
I would be happy to accept a PR to upgrade to the latest stack LTS snapshot.

For the Setup.hs use of git, the patch in the existing nix formula seemed to work well: https://github.com/NixOS/nixpkgs/blob/2c50340575a4b91bd983894d294e5619ae4aee96/pkgs/development/compilers/elm/packages/elm-format.nix#L34-L37

If you have a better suggestion for how to set up the project to automatically have a correct version number for all builds (including dev builds) that's different from calling git in Setup.hs, I'd be happy to hear about.  The reason for the git call in the first place is that I wanted to make sure that binaries build from any commit would include an appropriate version number so that any elm-format binary could be easily identified.

**Comment by avh4** [comment]
Also, can the updating of the nix package be automated in some way?  If you want to contribute a PR to this repo to add a `package/nix` folder with a script or instructions that I can follow whenever I do a new elm-format release, I'd be happy to help kick off the updates of the nix package.

**Comment by basile-henry** [comment]
One option would be to use something like the [`gitrev`](https://hackage.haskell.org/package/gitrev-1.3.1/docs/Development-GitRev.html) package to get the git commit at compile time? Then the `nix` derivation just needs to add `git` as a build dependency.

I was curious how `gitrev` is used across packages in `nixpkgs`, so I looked at the [hackage reverse dependencies for `gitrev`](https://packdeps.haskellers.com/reverse/gitrev) and picked the first package: `Agda`. It looks like nothing special is done to depend on `git` for `Agda` (neither `Agda` or `gitrev` depend on `git`) in `nixpkgs`.

If `gitrev` doesn't have access to `git` it returns an `UNKNOWN` revision. This is how `Agda` deals with `UNKNOWN` values: https://github.com/agda/agda/blob/d7e3a5883c918abaebe28f9d05ddc74c9ac88a6c/src/full/Agda/VersionCommit.hs#L17

So if you get `Agda` from `nixpkgs` you don't have access to the `git` revision it was built with. :confused: 

Maybe patching `Setup.hs` with the `git` revision is not too bad, it would be nice to use a variable for the `fetchgit` revision on the patch though, so they don't get out of sync. But if the derivation is be generated, then it's fine like as it is.

I'll can try to write a script to automate writing the nix derivation! :smile:

**Comment by avh4** [comment]
Updating the nix package is now part of the elm-format deploy process.  Thanks for the help!
