### ISSUE TITLE
Should print errors to stderr (not stdout) when formatting `--stdin`

### ISSUE THREAD

**Issue by lassik** [avh4/elm-format#560]
Currently some error messages are written to stdout, so tools that expect to gather errors from stderr (because they expect to read the formatted code from stdout) will not be able to find those messages and show them to users. Would it be feasible to have a policy to always write all error messages to stderr?

Technically, errors only seem to be written to stdout when the exit code is nonzero, so in that case callers could merge the contents of stdout and stderr to get all the messages, but it would seem much simpler for elm-format to always write all errors to stderr.

At least some of the errors going to stdout can be found by searching for `putStr` in [ElmFormat.hs](https://github.com/avh4/elm-format/blob/master/src/ElmFormat.hs). Might be worth verifying [all `putStr` calls in the codebase](https://github.com/avh4/elm-format/search?q=putstr&unscoped_q=putstr).

**Comment by avh4** [comment]
Is it not common for such tools to collect both the stdout and stderr?  Or is the tool you are writing using the `--stdout` option of elm-format?  With `--stdout`, I agree that printing anything other than the formatted file to stdout would be bad.  But for other cases I am less sure, since I think someone using elm-format from the terminal should be primarily interacting with stdin/stdout.

Also, I am wondering if it would be better to have some machine-readable output format for tools to use, or do you only intend to pass it directly through to show the user rather than trying to parse the error message output?

**Comment by lassik** [comment]
Yes, we're using `--stdin` to format code from stdin to stdout.

In other cases, I don't know which is more common - merging stdout and stderr, or collecting only stderr. They are merged by default when calling programs interactively from the terminal, but when calling them programmatically the situation is less clear. Pipes and redirects work more naturally when all error/warning messages go to stderr, since e.g. in shell one can simply write `elm-format 2>errors.log`. Redirecting both stdout and stderr is more complicated (`elm-format 2>errors.log 1>&2`). Likewise, it tends to be more complicated to merge stdout and stderr when setting up subprocess pipes in some programming language - you either have to set up two pipes instead of one, or duplicate the stdout file descriptor to equal the stderr file descriptor using the Unix `dup2()` system call (fd duplication is quite specialized so it's probably not available in most programming languages).

Continuing discussion about machine-readable error output (JSON/XML) in #388

**Comment by avh4** [comment]
Okay, thanks!  I'm gonna rename this issue to specifically focus on fixing things for `--stdin`

**Comment by lassik** [comment]
Thanks :) That would solve our use case.

**Comment by avh4** [comment]
I fixed this for normal errors in https://github.com/avh4/elm-format/pull/614.  Thanks for the report!
