### ISSUE TITLE
Format multiple files in a single run

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#67]
`elm-format` should accept more than a single file or directory to be given on the command line.

If multiple files are given, specifying `--output` should be an error.

**Comment by eeue56** [comment]
+1, it was the first thing that I tried. If I get time I'll look into this

**Comment by avh4** [comment]
FYI, currently you can specify a directory, and all `*.elm` files in that directory will be formatted.

But a contribution would be great.  `src/Main.hs`, and `src/Flags.hs` are the place to start.

**Comment by eeue56** [comment]
Ah, perfect! That saves me some time :)

**Comment by eeue56** [comment]
Okay, so I have a working implementation [here](https://github.com/eeue56/elm-format/tree/handle-multiple-files)

I have some questions that you might be able to answer:

- What's the expected behaviour when one of the files passed in isn't found or isn't a valid Elm path?
- Should the `output` flag be ignored when multiple paths are given? I assume so, since that's what happens when you give it a `dir` 
- Should it recurse into directories by default? Eg, if you do `elm-format src` should it then go and format those in `src/Http/` too?

**Comment by avh4** [comment]
If `--output` is specified when there are multiple files given, we should exit with an error message.

Recursion should use `findAllElmFiles` in https://github.com/avh4/elm-format/blob/master/src/ElmFormat/Filesystem.hs which does recurse into subdirectories.

If some files are errors and others are fine, we haven't completely decided what to do.  But specifying multiple files should be consistent with specifying a directory that contains multiple files.

**Comment by eeue56** [comment]
I opened a PR #69 to fix this - let me know what you think!

**Comment by avh4** [comment]
Fixed in #69
