### ISSUE TITLE
Update jsprim dependency to 1.4.2

### ISSUE THREAD

**Issue by micahhahn** [avh4/elm-format#757]
Can we bump the version of `jsprim` to 1.4.2?   `jsprim` 1.4.1 depends on `json-schema` 0.2.3 which has a prototype pollution vulnerability

**Comment by lydell** [comment]
Hi! I’m not the maintainer of elm-format, but thought I’d chime in with what I know. I ran `npm install elm-format` in a new directory (with npm 7), and I got jsprim 1.4.2 installed. This is the dependency chain:

```
❯ npm-why jsprim

  Who required jsprim:

  my-test-project > elm-format > binwrap > request > http-signature > jsprim@1.4.2
```

It looks like semver is working as intended here: The whole chain is using version ranges properly, so no changes are required by any package authors.

I think jsprim is locked to 1.4.1 by your lock file (package-lock.json if you use npm), or maybe due to some other package you depend on. An easy way to check that is to delete the lock file and then run `npm install` to get a fresh install. If that works, you’ll need to decide if you’re ok with the full lock file nuke, or if you’d like to find another way of just updating the jsprim chain (not sure how to do that off the top of my head).

(Shameless plug: If you would like to not depend on jsprim and suchlike modules at all, you could install elm-format with [elm-tooling](https://elm-tooling.github.io/elm-tooling-cli/) instead.)

**Comment by micahhahn** [comment]
Ah thank you! Re-running `npm install elm-format` was enough to update the `jsprim` version in my `package-lock.json` file.
